"""
ai_replay.py - AI Decision Replay & Benchmarking Strategy.

Replays historical AI decisions captured in trade.db (ai_snapshots table).
Allows backtesting variations of risk management (different TSL ladders, SL/targets)
against the exact real-time signals generated by the bot's AI brain.
"""

from typing import Dict, Any, Optional, List
from ..base_strategy import BaseStrategy, Signal
from ..parameter_space import Parameter
from data.data_loader import DataLoader


class AiReplayStrategy(BaseStrategy):
    """
    Historical AI Decision Replayer.
    Feeds actual Gemini decisions recorded during live market hours back into the trade simulator.
    """

    def __init__(self, data_loader: Optional[DataLoader] = None):
        super().__init__(
            name="AI Historical Replay",
            description="Replay the exact historical decisions of Gemini from trade.db with configurable SL/TSL rules.",
            category="AI_REPLAY"
        )
        self.data_loader = data_loader or DataLoader()
        self.current_day_snapshots: List[Dict[str, Any]] = []
        self.snapshot_idx = 0
        self.cached_date = ""

    def _setup_parameters(self) -> None:
        self.parameters.add(Parameter("min_confidence", "float", 0.70, 0.5, 0.95, 0.05, description="Min confidence to trigger entry"))
        self.parameters.add(Parameter("stop_loss_pts", "float", 15.0, 5.0, 35.0, 2.5, description="Stop loss points override"))
        self.parameters.add(Parameter("target_pts", "float", 30.0, 10.0, 70.0, 5.0, description="Target profit points override"))

    def reset(self) -> None:
        self.snapshot_idx = 0

    def _load_day_if_needed(self, date_str: str) -> None:
        if self.cached_date != date_str:
            if hasattr(self.data_loader, "load_ai_snapshots"):
                self.current_day_snapshots = self.data_loader.load_ai_snapshots(date_str)
            elif hasattr(self.data_loader, "get_ai_snapshots"):
                df = self.data_loader.get_ai_snapshots(date_str)
                self.current_day_snapshots = [{str(k): v for k, v in r.items()} for r in df.to_dict(orient="records")] if (df is not None and not df.empty) else []
            else:
                self.current_day_snapshots = []
            self.cached_date = date_str
            self.snapshot_idx = 0

    def on_candle(
        self,
        candle: Dict[str, Any],
        history: List[Dict[str, Any]],
        context: Optional[Dict[str, Any]] = None
    ) -> Optional[Signal]:
        date_str = str(context.get("date", "")) if context else ""
        if not date_str:
            return None

        self._load_day_if_needed(date_str)
        if not self.current_day_snapshots or self.snapshot_idx >= len(self.current_day_snapshots):
            return None

        candle_time = str(candle.get("candle_time", ""))

        # Find snapshots occurring around this candle
        while self.snapshot_idx < len(self.current_day_snapshots):
            snap = self.current_day_snapshots[self.snapshot_idx]
            snap_time = str(snap.get("snapshot_time", ""))

            # If snapshot is ahead of candle, wait for future candle
            if snap_time > candle_time and candle_time != "":
                break

            self.snapshot_idx += 1

            action = str(snap.get("parsed_action", "WAIT")).upper()
            conf = float(snap.get("parsed_confidence", 0.0) or 0.0)

            if conf >= self.current_params["min_confidence"]:
                bias = str(snap.get("parsed_bias", "NEUTRAL")).upper()
                opt_type = None

                # First try direct JSON payload
                raw_json = snap.get("parsed_signal_json")
                if raw_json:
                    try:
                        import json
                        p_data = json.loads(raw_json)
                        opt_type = p_data.get("option_type")
                    except Exception:
                        pass

                if not opt_type:
                    if bias in ("CALL", "BULLISH", "LONG"):
                        opt_type = "CE"
                    elif bias in ("PUT", "BEARISH", "SHORT"):
                        opt_type = "PE"

                cur_close = float(candle.get("close", 0))


                if action == "ENTER" and opt_type:
                    return Signal(
                        action="ENTER",
                        market_bias=bias,
                        option_type=opt_type,
                        strike=round(cur_close / 50.0) * 50.0,
                        entry_price=cur_close,
                        stop_loss=self.current_params["stop_loss_pts"],
                        target=self.current_params["target_pts"],
                        confidence=conf,
                        reasoning=str(snap.get("parsed_reasoning", "Recorded AI Decision")),
                        timestamp=snap_time,
                        metadata={"ai_snapshot_id": snap.get("id"), "original_action": action}
                    )
                elif action == "EXIT_NOW":
                    return Signal(
                        action="EXIT_NOW",
                        confidence=conf,
                        reasoning=str(snap.get("parsed_reasoning", "AI Forced Exit")),
                        timestamp=snap_time
                    )

        return None
